name: GameMenu
version: '${project.version}'
main: xyz.kragleh.gamemenu.GameMenu
load: STARTUP
depend: [ DeluxeMenus ]
authors: [ kragleh ]
description: Plugin used to make a clickable item in players inventory that executes a command to a menu.
